services:
  - type: web
    name: tts-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"