services:
  - type: web
    name: tts-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    region: oregon
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"